version: '3.8'
services:

  web:
    container_name: web
    build:
      context: ./web  
      dockerfile: Dockerfile  
    restart: always
    environment:
      - NODE_ENV=production
    ports:
      - "80:80"



  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: admin123
      MINIO_ROOT_PASSWORD: admin123
    networks:
      - minio_network

networks:
  minio_network:
    driver: bridge

volumes:
  minio_data:
    driver: local
